-- Core task aggregate; timestamps represent absolute instants.
-- 核心任务聚合；时间戳表示绝对时间点。
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Tags are normalized into rows for indexed filtering.
-- 标签按行规范化存储，以支持索引筛选。
CREATE TABLE task_tags (
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    tag VARCHAR(50) NOT NULL,
    PRIMARY KEY (task_id, tag)
);

-- Directed dependency edges are protected by FK and self-cycle constraints.
-- 有向依赖边由外键和自依赖约束共同保护。
CREATE TABLE task_dependencies (
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    depends_on_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, depends_on_id),
    CONSTRAINT no_self_dependency CHECK (task_id <> depends_on_id)
);

-- Cover the primary list filters and reverse dependency lookup.
-- 覆盖主要列表筛选及反向依赖查询。
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_priority ON tasks(priority);
CREATE INDEX idx_tasks_created_at ON tasks(created_at DESC);
CREATE INDEX idx_task_tags_tag ON task_tags(tag);
CREATE INDEX idx_dependencies_depends_on ON task_dependencies(depends_on_id);
