-- Accounts are the tenancy boundary for every task row.
-- 用户账号是所有任务行的租户边界。
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Existing demo tasks have no owner; drop them instead of inventing a fake user.
-- 已有演示任务没有归属用户，直接删除而不是伪造账号。
DELETE FROM tasks;

ALTER TABLE tasks ADD COLUMN owner_id BIGINT NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_owner
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX idx_tasks_owner_created ON tasks(owner_id, created_at DESC, id DESC);

-- Store owner-prefixed retry keys without colliding across accounts.
-- 存储带用户前缀的重试 Key，避免跨账号冲突。
ALTER TABLE idempotency_records ALTER COLUMN idempotency_key TYPE VARCHAR(140);
